### PR TITLE
Minor Bug Fixes

### PR DESCRIPTION
**Pull request by Zoolyn**
Healthy Habits Pages:
-Fixed Exit button placement (made sure the button is not off screen)
-Enlarged text across the line
Going on an Adventure:
-Changed background color of the location selection buttons from light blue to grey
-Changed the item buttons to match the location selection buttons
-Added shadows to all the boxes

### CODE REVIEW

**Review by GabrielMarquez0852 — APPROVED** [review]
Looks good

**Review by laport14 — COMMENTED** [review]
good to go!

**Review by laport14 — APPROVED** [review]
good to go!

**Review by xpetrus — APPROVED** [review]
yes yes yes

**Pull request merged**
