### PR TITLE
Cash shop frontend

### PR DESCRIPTION
**Pull request by jackzhen1996**
**Features completed**:
1. Purchase by accessory view
  - filter through different categories of clothing items 
  - clothing items are divided into sub-categories to ensure one clothing item per body part
  - can preview the selected items before proceeding to checkout
  - can deselect clothing item
2. Purchase by outfit view
  - can purchase a bundle of clothing items
3. Checkout modal
  - can preview the selected items, or delete items before final purchase
4. Wardrobe view
  - same stuff as 1st feature, but without the ability to go to checkout page

**Work-in-progress**:
1. Redux actions 
2. Style check for different screen sizes

### CODE REVIEW

**Review by GabrielMarquez0852 — APPROVED** [review]
this looks good

**Comment by ArKane-6418** [comment]
There are lots of logging statements, I think we should remove them from the PR

**Comment by ArKane-6418** [comment]
If you have time, you can remove them, but we're going to approve it

**Review by ArKane-6418 — COMMENTED** [review]
Looks good, if you can remove the debugging statements later on, that'd be great

**Review by ArKane-6418 — APPROVED** [review]
Looks good, if you can remove the debugging statements later on, that'd be great

**Pull request merged**
